import { useCallback, useState } from 'react';
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/providers/AuthProvider';

export default function ProfileScreen(){const{session}=useAuth();const[name,setName]=useState('');const[budget,setBudget]=useState('');const[interests,setInterests]=useState('');const[transportation,setTransportation]=useState('');const[saving,setSaving]=useState(false);
const load=useCallback(async()=>{if(!session?.user.id)return;const{data,error}=await supabase.from('profiles').select('display_name,budget,interests,transportation').eq('id',session.user.id).single();if(error){console.error(error);return}setName(data.display_name??'');setBudget(data.budget==null?'':String(data.budget));setInterests((data.interests??[]).join(', '));setTransportation(data.transportation??'')},[session?.user.id]);useFocusEffect(useCallback(()=>{void load()},[load]));
async function save(){if(!session?.user.id)return;const parsed=budget.trim()===''?null:Number(budget);if(parsed!==null&&(!Number.isFinite(parsed)||parsed<0))return Alert.alert('Invalid budget','Enter a non-negative number.');try{setSaving(true);const{error}=await supabase.from('profiles').update({display_name:name.trim()||'User',budget:parsed,interests:interests.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),transportation:transportation.trim()||null}).eq('id',session.user.id);if(error)throw error;Alert.alert('Saved','Your preferences are updated.')}catch(e){Alert.alert('Could not save',e instanceof Error?e.message:'Something went wrong.')}finally{setSaving(false)}}
return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Profile</Text><Text style={styles.label}>Display name</Text><TextInput style={styles.input} value={name} onChangeText={setName}/><Text style={styles.label}>Personal budget</Text><TextInput style={styles.input} value={budget} onChangeText={setBudget} keyboardType="decimal-pad" placeholder="20"/><Text style={styles.label}>Interests</Text><TextInput style={styles.input} value={interests} onChangeText={setInterests} placeholder="cafes, parks, music"/><Text style={styles.label}>Transportation</Text><TextInput style={styles.input} value={transportation} onChangeText={setTransportation} placeholder="walking, transit, car…"/><Pressable style={styles.button} onPress={save} disabled={saving}><Text style={styles.buttonText}>{saving?'Saving…':'Save profile'}</Text></Pressable><Pressable style={styles.signout} onPress={()=>void supabase.auth.signOut()}><Text>Sign out</Text></Pressable></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({container:{flex:1},content:{padding:24,gap:10},title:{fontSize:30,fontWeight:'700',marginBottom:8},label:{fontWeight:'600',marginTop:6},input:{borderWidth:1,borderColor:'#ddd',borderRadius:12,padding:14,fontSize:16},button:{backgroundColor:'#111',padding:16,borderRadius:12,alignItems:'center',marginTop:14},buttonText:{color:'#fff',fontWeight:'700'},signout:{alignItems:'center',padding:16,marginTop:6}});
