import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { getMyGroups, joinGroup, type GroupSummary } from '@/lib/groups';
import { Alert, TextInput } from 'react-native';

export default function GroupsScreen(){const[groups,setGroups]=useState<GroupSummary[]>([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[code,setCode]=useState('');const[joining,setJoining]=useState(false);
const load=useCallback(async()=>{try{setGroups(await getMyGroups())}catch(e){console.error(e)}finally{setLoading(false);setRefreshing(false)}},[]);useFocusEffect(useCallback(()=>{void load()},[load]));
async function join(){if(!code.trim())return Alert.alert('Missing code','Enter a six-character invite code.');try{setJoining(true);const id=await joinGroup(code);setCode('');router.push({pathname:'/group/[id]',params:{id}})}catch(e){Alert.alert('Could not join group',e instanceof Error?e.message:'Something went wrong.')}finally{setJoining(false)}}
return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load()}}/>}><Text style={styles.title}>Your groups</Text><Pressable style={styles.primary} onPress={()=>router.push('/group/create')}><Text style={styles.primaryText}>Create group</Text></Pressable><View style={styles.joinRow}><TextInput style={styles.input} placeholder="Invite code" autoCapitalize="characters" maxLength={6} value={code} onChangeText={v=>setCode(v.toUpperCase())}/><Pressable style={styles.joinButton} onPress={join} disabled={joining}><Text style={styles.primaryText}>{joining?'Joining…':'Join'}</Text></Pressable></View>{loading?<ActivityIndicator size="large"/>:groups.length===0?<Text style={styles.empty}>No groups yet.</Text>:groups.map(g=><Pressable key={g.id} style={styles.card} onPress={()=>router.push({pathname:'/group/[id]',params:{id:g.id}})}><Text style={styles.name}>{g.name}</Text><Text style={styles.meta}>{g.join_code??'No code'} · {g.budget==null?'Default budget':`$${Number(g.budget).toFixed(2)}/person`}</Text></Pressable>)}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({container:{flex:1},content:{padding:24,gap:14},title:{fontSize:30,fontWeight:'700'},primary:{backgroundColor:'#111',padding:15,borderRadius:12,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'700'},joinRow:{flexDirection:'row',gap:8},input:{flex:1,borderWidth:1,borderColor:'#ddd',borderRadius:12,padding:13,fontSize:16},joinButton:{backgroundColor:'#111',borderRadius:12,paddingHorizontal:20,justifyContent:'center'},empty:{opacity:.6,textAlign:'center',marginTop:30},card:{borderWidth:1,borderColor:'#e8e8e8',borderRadius:14,padding:16},name:{fontSize:18,fontWeight:'700'},meta:{opacity:.6,marginTop:5}});
